name = "Schildi: Residenz Life"
author = "Flumuffel"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a909085e14fdf3395269d99306dd8307eb1a49738298cbabb0ae9dbe7381947"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"
