name = "Schildi: Residenz Life"
author = "Flumuffel"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b713c1347e9e0c09eddc915124b9154f0b5ae7a9d6bf976d2d01c0f3aebbc7cf"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"
